"""
Core data models for DRETL.

These models define the structure of dataset reports and rewrite plans
that flow through the ETL pipeline.
"""

from dataclasses import dataclass, field
from typing import List, Dict, Any, Optional
from enum import Enum


class GeometryType(Enum):
    """Supported geometry types."""
    POINT = "Point"
    LINESTRING = "LineString"
    POLYGON = "Polygon"
    MULTIPOINT = "MultiPoint"
    MULTILINESTRING = "MultiLineString"
    MULTIPOLYGON = "MultiPolygon"
    GEOMETRYCOLLECTION = "GeometryCollection"
    UNKNOWN = "Unknown"


class FieldType(Enum):
    """Supported field/column types."""
    STRING = "string"
    INTEGER = "integer"
    FLOAT = "float"
    BOOLEAN = "boolean"
    DATE = "date"
    DATETIME = "datetime"
    GEOMETRY = "geometry"
    UNKNOWN = "unknown"


@dataclass
class FieldInfo:
    """Information about a field/column in a layer."""
    name: str
    field_type: FieldType
    nullable: bool = True
    max_length: Optional[int] = None
    precision: Optional[int] = None
    scale: Optional[int] = None
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary representation."""
        return {
            "name": self.name,
            "type": self.field_type.value,
            "nullable": self.nullable,
            "max_length": self.max_length,
            "precision": self.precision,
            "scale": self.scale,
        }


@dataclass
class LayerInfo:
    """Information about a layer in a dataset."""
    name: str
    geometry_type: GeometryType
    feature_count: int
    crs: Optional[str] = None  # Coordinate Reference System (e.g., "EPSG:4326")
    bbox: Optional[tuple] = None  # Bounding box (minx, miny, maxx, maxy)
    fields: List[FieldInfo] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary representation."""
        return {
            "name": self.name,
            "geometry_type": self.geometry_type.value,
            "feature_count": self.feature_count,
            "crs": self.crs,
            "bbox": self.bbox,
            "fields": [f.to_dict() for f in self.fields],
            "metadata": self.metadata,
        }


@dataclass
class DatasetReport:
    """
    READ-ONLY report generated by handlers after inspecting a dataset.
    
    This is the output of the detection phase and contains all information
    needed to plan a rewrite operation.
    """
    source_path: str
    source_type: str  # e.g., "gpkg", "shapefile", "geojson", "postgis"
    layers: List[LayerInfo] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)
    errors: List[str] = field(default_factory=list)
    warnings: List[str] = field(default_factory=list)
    
    @property
    def is_valid(self) -> bool:
        """Check if the dataset report is valid (no errors)."""
        return len(self.errors) == 0
    
    @property
    def layer_count(self) -> int:
        """Get the number of layers in the dataset."""
        return len(self.layers)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary representation."""
        return {
            "source_path": self.source_path,
            "source_type": self.source_type,
            "layers": [layer.to_dict() for layer in self.layers],
            "metadata": self.metadata,
            "errors": self.errors,
            "warnings": self.warnings,
        }


@dataclass
class RewriteOptions:
    """Options for controlling the rewrite operation."""
    layer_name: Optional[str] = None  # Target layer name (if renaming)
    srid: Optional[int] = None  # Target SRID for reprojection
    truncate: bool = False  # Truncate target before writing
    append: bool = False  # Append to existing data
    overwrite: bool = True  # Overwrite existing layer/table
    chunk_size: int = 1000  # Batch size for writing features
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary representation."""
        return {
            "layer_name": self.layer_name,
            "srid": self.srid,
            "truncate": self.truncate,
            "append": self.append,
            "overwrite": self.overwrite,
            "chunk_size": self.chunk_size,
        }


@dataclass
class RewritePlan:
    """
    WRITE plan consumed by targets to execute the data transformation.
    
    This is generated from a DatasetReport and contains instructions
    for how to rewrite the data.
    """
    report: DatasetReport
    target_type: str  # e.g., "postgis", "gpkg", "geojson"
    target_path: str  # Connection string, file path, etc.
    options: RewriteOptions = field(default_factory=RewriteOptions)
    selected_layers: Optional[List[str]] = None  # None = all layers
    
    @property
    def layers_to_process(self) -> List[LayerInfo]:
        """Get the list of layers that will be processed."""
        if self.selected_layers is None:
            return self.report.layers
        return [
            layer for layer in self.report.layers
            if layer.name in self.selected_layers
        ]
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary representation."""
        return {
            "report": self.report.to_dict(),
            "target_type": self.target_type,
            "target_path": self.target_path,
            "options": self.options.to_dict(),
            "selected_layers": self.selected_layers,
        }
